name: hero
version: 1.0.3+20
publish_to: none
description: The Carpedia Hero app create by HaziqJen
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.6
  flutter:
    sdk: flutter
  #LIBRARY ----------------------------------------------------------
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  shimmer: ^3.0.0
  animate_do: ^3.0.2
  path_provider: ^2.0.15
  lottie: ^2.4.0
  dio: ^5.2.1+1
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  dio_cache_interceptor: ^3.4.2
  fluttertoast: ^8.2.2
  pull_to_refresh_flutter3: ^2.0.2
  badges: ^3.1.1
  font_awesome_flutter: ^10.5.0
  flutter_advanced_drawer: ^1.3.5
  pretty_dio_logger: ^1.3.1
  permission_handler: ^10.4.2
  geolocator: ^9.0.2
  flutter_local_notifications: ^15.1.0+1
  #  flutter_native_timezone: ^2.0.0
  image: ^4.0.17
  device_info_plus: ^9.0.2
  line_icons: ^2.0.3
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  easy_mask: ^2.0.1
  confetti: ^0.7.0
  iconly: ^1.0.1
  #  google_places_flutter: ^2.0.5
  #  google_maps_flutter: ^2.2.5
  #  flutter_svg: ^2.0.4
  encrypt: ^5.0.1
#  flutter_slidable: ^3.0.0
  image_picker: ^1.0.0
  file_picker: ^5.3.2
  otp_text_field: ^1.1.3
  expandable: ^5.0.1
  timeago: ^3.5.0
  carousel_slider: ^4.2.1
  searchfield: ^0.8.4
  calendar_date_picker2: ^0.5.3
  dropdown_button2: ^2.3.9
  auto_size_text: ^3.0.0
  fl_chart: ^0.64.0
  multi_dropdown: ^2.1.1
  youtube_player_flutter: ^8.1.2
  easy_image_viewer: ^1.3.2
  url_launcher: ^6.2.4

  #FIREBASE ------------------------------
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  #FIREBASE -----------------------------


  #LIBRARY ----------------------------------------------------------

dev_dependencies:
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/sounds/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/SFProRegular.ttf

    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/SFProMedium.ttf

    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/SFProSemibold.ttf

    - family: GilroyBold
      fonts:
        - asset: assets/fonts/SFProBold.ttf



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
