// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwH9rEQp_AiJ9UKOI1dzECgBassvBYO7U',
    appId: '1:321779242842:web:1d43035bd95aa838ba0563',
    messagingSenderId: '321779242842',
    projectId: 'carpedia-driver-app',
    authDomain: 'carpedia-driver-app.firebaseapp.com',
    storageBucket: 'carpedia-driver-app.appspot.com',
    measurementId: 'G-HH0Q9TMC67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkMKuftr1RUELBV8kNM1ESxE8mECO6ftI',
    appId: '1:321779242842:android:412343a8aad00e3fba0563',
    messagingSenderId: '321779242842',
    projectId: 'carpedia-driver-app',
    storageBucket: 'carpedia-driver-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI42Axpv25PBlxkxonpKdf_hUehET7ciQ',
    appId: '1:321779242842:ios:7244377419ba6e07ba0563',
    messagingSenderId: '321779242842',
    projectId: 'carpedia-driver-app',
    storageBucket: 'carpedia-driver-app.appspot.com',
    androidClientId: '321779242842-e22h5drnrhhke6dgou53b0dgf1u1juvj.apps.googleusercontent.com',
    iosBundleId: 'com.thecarpedia.hero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI42Axpv25PBlxkxonpKdf_hUehET7ciQ',
    appId: '1:321779242842:ios:a36afb836590a46eba0563',
    messagingSenderId: '321779242842',
    projectId: 'carpedia-driver-app',
    storageBucket: 'carpedia-driver-app.appspot.com',
    androidClientId: '321779242842-e22h5drnrhhke6dgou53b0dgf1u1juvj.apps.googleusercontent.com',
    iosBundleId: 'com.thecarpedia.hero.RunnerTests',
  );
}
